# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: enonic

before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...

env_files:
  github_token: ./configs/goreleaser.github.token

builds:
 # You can have multiple builds defined as a yaml list
-

# Path to main.go file or main package.
# Default is `.`.
  main: ./internal/app/cli.go

# Name template for the binary final name.
# Default is the name of the project directory.
  binary: enonic

# Custom environment variables to be set during the builds.
# Default is empty.
  env:
  - CGO_ENABLED=0

# GOOS list to build for.
# For more info refer to: https://golang.org/doc/install/source#environment
# Defaults are darwin and linux.
  goos:
  - linux
  - darwin
  - windows

# GOARCH to build for.
# For more info refer to: https://golang.org/doc/install/source#environment
# Defaults are 386 and amd64.
  goarch:
  - amd64

archive:
  replacements:
    darwin: Mac
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit

  format: tar.gz  # set to binary to omit archiving

  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: enonic
    name: xp-cli-scoop

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: true

scoop:
  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  url_template: http://repo.enonic.com/public/com/enonic/cli/{{ .ProjectName }}/{{ .Version }}/

  # Repository to push the app manifest to.
  bucket:
    owner: enonic
    name: xp-cli-scoop

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Your app's homepage.
  # Default is empty.
  homepage: "http://enonic.com/"

  # Your app's description.
  # Default is empty.
  description: "Enonic XP command line interface."

  # Your app's license
  # Default is empty.
  license: GPLv3

  # Persist data between application updates
#  persist:
#  - "data"
#  - "config.toml"

brew:

  # Repository to push the tap to.
  github:
    owner: enonic
    name: xp-cli-brew

  # Template for the url.
  # Default is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  url_template: http://repo.enonic.com/public/com/enonic/cli/{{ .ProjectName }}/{{ .Version }}/

  # Allows you to set a custom download strategy.
  # Default is empty.
#  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "http://enonic.com/"

  # Your app's description.
  # Default is empty.
  description: "Enonic XP command line interface."

nfpm:
  # You can change the name of the package.
  # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  # Replacements for GOOS and GOARCH in the package name.
  # Keys should be valid GOOSs or GOARCHs.
  # Values are the respective replacements.
  # Default is empty.
  replacements:
    darwin: Mac
    linux: Linux
    windows: Windows
    amd64: 64-bit
    386: 32-bit

  # Your app's vendor.
  # Default is empty.
  vendor: Enonic AS.
  # Your app's homepage.
  # Default is empty.
  homepage: http://enonic.com/

  # Your app's maintainer (probably you).
  # Default is empty.
  maintainer: Pavel Milkevich <pmi@enonic.com>

  # Your app's description.
  # Default is empty.
  description: Enonic XP command line interface.

  # Your app's license.
  # Default is empty.
  license: GPLv3

  # Formats to be generated.
  formats:
    - deb
#    - rpm  // rpm-build not present on windows, uncomment if built on linux or osx (rpm-build should be installed)

artifactories:
  - name: repo
    target: http://repo.enonic.com/public/com/enonic/cli/{{ .ProjectName }}/{{ .Version }}/
    username: ci
